/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierAdmin;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class SupplierManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierManageOrganizationJPanel
     */
    private JPanel userProcessContainer;
    private OrganizationDirectory directory;
    private EcoSystem system;

    public SupplierManageOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory directory, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        this.system = system;
        populateTable();
        populateCombo();
    }

    private void populateCombo() {
        jcbOrganization.removeAllItems();
        jcbOrganization.addItem(Organization.Type.Supplier);

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrganization.getModel();

        model.setRowCount(0);

        for (Organization organization : directory.getOrganizationList()) {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbOrganization = new javax.swing.JComboBox();
        btnCreateOrganization = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrganization.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        tblOrganization.setForeground(new java.awt.Color(102, 0, 102));
        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Organization Id", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganization);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 450, 130));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setText("Activity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, -1, -1));

        lblCustomername1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblCustomername1.setText("Organization");
        add(lblCustomername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 160, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel7.setText("Organization Type");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 140, -1));

        jcbOrganization.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jcbOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jcbOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, 208, 29));

        btnCreateOrganization.setBackground(new java.awt.Color(102, 102, 102));
        btnCreateOrganization.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnCreateOrganization.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateOrganization.setText("Add Organization");
        btnCreateOrganization.setMaximumSize(new java.awt.Dimension(200, 200));
        btnCreateOrganization.setMinimumSize(new java.awt.Dimension(200, 200));
        btnCreateOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrganizationActionPerformed(evt);
            }
        });
        add(btnCreateOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 223, 39));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, -1, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrganizationActionPerformed
        // TODO add your handling code here:
        Organization.Type type = (Organization.Type) jcbOrganization.getSelectedItem();
        directory.createOrganization(type);
        System.out.println("Org type" + type);
        populateTable();
    }//GEN-LAST:event_btnCreateOrganizationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateOrganization;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbOrganization;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JTable tblOrganization;
    // End of variables declaration//GEN-END:variables
}
