/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author
 */
public class SupplierAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem system;

    public SupplierAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        btnMngOrg = new javax.swing.JButton();
        btnMngEmployee = new javax.swing.JButton();
        btnMngUser = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setText("Activity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 110, -1));

        lblCustomername1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblCustomername1.setText("Administrative(Enterprise) Work Area JPanel ");
        add(lblCustomername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 520, -1));

        btnMngOrg.setBackground(new java.awt.Color(102, 102, 102));
        btnMngOrg.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnMngOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnMngOrg.setText("Manage Organization");
        btnMngOrg.setMaximumSize(new java.awt.Dimension(200, 200));
        btnMngOrg.setMinimumSize(new java.awt.Dimension(200, 200));
        btnMngOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngOrgActionPerformed(evt);
            }
        });
        add(btnMngOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 223, 60));

        btnMngEmployee.setBackground(new java.awt.Color(102, 102, 102));
        btnMngEmployee.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnMngEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnMngEmployee.setText("Manage Employee");
        btnMngEmployee.setMaximumSize(new java.awt.Dimension(200, 200));
        btnMngEmployee.setMinimumSize(new java.awt.Dimension(200, 200));
        btnMngEmployee.setPreferredSize(new java.awt.Dimension(169, 25));
        btnMngEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngEmployeeActionPerformed(evt);
            }
        });
        add(btnMngEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 223, 60));

        btnMngUser.setBackground(new java.awt.Color(102, 102, 102));
        btnMngUser.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnMngUser.setForeground(new java.awt.Color(255, 255, 255));
        btnMngUser.setText("Manage User");
        btnMngUser.setMaximumSize(new java.awt.Dimension(200, 200));
        btnMngUser.setMinimumSize(new java.awt.Dimension(200, 200));
        btnMngUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngUserActionPerformed(evt);
            }
        });
        add(btnMngUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, 223, 60));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel7.setText("Enterprise :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 100, -1));

        valueLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        valueLabel.setText("*Enterprise");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngOrgActionPerformed
        // TODO add your handling code here:
        SupplierManageOrganizationJPanel orgJPanel = new SupplierManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), system);
        userProcessContainer.add("organization JPanel", orgJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnMngOrgActionPerformed

    private void btnMngEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngEmployeeActionPerformed
        // TODO add your handling code here:
        SupplierlManageEmployeeJPanel manageEmployeeJPanel = new SupplierlManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), system);
        userProcessContainer.add("Manage Enterprise JPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngEmployeeActionPerformed

    private void btnMngUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngUserActionPerformed
        // TODO add your handling code here:
        SupplierlManageUserAccountJPanel manageUserAccountJPanel = new SupplierlManageUserAccountJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("Enterprise Admin JPanel", manageUserAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngEmployee;
    private javax.swing.JButton btnMngOrg;
    private javax.swing.JButton btnMngUser;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
