/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommonLoginPage;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodRequest;
import Business.WorkQueue.QualityCheckRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class CallQualityCheckerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CallQualityCheckerJPanel
     */
    private JPanel container;
    private UserAccount ua;
    private FoodRequest foodReq;
    private Organization org;
    private Enterprise enterprise;
    private EcoSystem system;
    private QualityCheckRequest qualCheckReq;

    public CallQualityCheckerJPanel(JPanel container, FoodRequest req, UserAccount ua, Organization org, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.foodReq = req;
        this.org = org;
        this.enterprise = enterprise;
        this.system = system;

        populateFoodRequest();

    }

    public void populateFoodRequest() {
        DefaultTableModel dtm = (DefaultTableModel) tblNotifyQualityChecker.getModel();
        dtm.setRowCount(0);

        Object row[] = new Object[7];
        row[0] = foodReq.getFood().getName();
        row[1] = foodReq.getFood().getCode();
        dtm.addRow(row);
    }

    public void populateTechnicianRequest() {
        DefaultTableModel dtm = (DefaultTableModel) tblNotifyQualityChecker.getModel();
        dtm.setRowCount(0);

        Object row[] = new Object[7];
        row[0] = qualCheckReq.getFood().getName();
        row[1] = qualCheckReq.getFood().getCode();
        row[2] = qualCheckReq.getStatus();
        row[3] = qualCheckReq.getReceiver();
        row[4] = ((QualityCheckRequest) qualCheckReq).getServiceDateInString();

        dtm.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotifyQualityChecker = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProblemDesc = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnViewReq = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        tblNotifyQualityChecker.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        tblNotifyQualityChecker.setForeground(new java.awt.Color(102, 0, 102));
        tblNotifyQualityChecker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Food", "Code", "Notify", "Quality Checker Name", "Possible date of Assistance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblNotifyQualityChecker);

        add(jScrollPane2);
        jScrollPane2.setBounds(650, 260, 779, 43);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(830, 180, 120, 30);

        lblCustomername1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblCustomername1.setText("Request for quality check");
        add(lblCustomername1);
        lblCustomername1.setBounds(950, 180, 300, 30);

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel7.setText("Notes");
        add(jLabel7);
        jLabel7.setBounds(840, 420, 60, 20);

        txtProblemDesc.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtProblemDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProblemDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProblemDescActionPerformed(evt);
            }
        });
        txtProblemDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProblemDescKeyPressed(evt);
            }
        });
        add(txtProblemDesc);
        txtProblemDesc.setBounds(900, 420, 286, 27);

        btnSend.setBackground(new java.awt.Color(102, 102, 102));
        btnSend.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.setMaximumSize(new java.awt.Dimension(200, 200));
        btnSend.setMinimumSize(new java.awt.Dimension(200, 200));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend);
        btnSend.setBounds(940, 500, 180, 37);

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(830, 500, 53, 39);

        btnViewReq.setBackground(new java.awt.Color(102, 102, 102));
        btnViewReq.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnViewReq.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReq.setText("View all Requests >");
        btnViewReq.setMaximumSize(new java.awt.Dimension(200, 200));
        btnViewReq.setMinimumSize(new java.awt.Dimension(200, 200));
        btnViewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReqActionPerformed(evt);
            }
        });
        add(btnViewReq);
        btnViewReq.setBounds(1250, 330, 180, 35);
    }// </editor-fold>//GEN-END:initComponents

    private void txtProblemDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProblemDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProblemDescActionPerformed

    private void txtProblemDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProblemDescKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtProblemDescKeyPressed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNotifyQualityChecker.getSelectedRow();
        if (selectedRow >= 0) {
            String des = txtProblemDesc.getText();
            String type = "";
            if (des.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter Description");
                return;
            } else {
                qualCheckReq = new QualityCheckRequest();
                qualCheckReq.setFood(foodReq.getFood());
                qualCheckReq.setSender(ua);
                org.getWorkQueue().getWorkRequestList().add(qualCheckReq);
                ua.getWorkQueue().getWorkRequestList().add(qualCheckReq);
                system.getWorkQueue().getWorkRequestList().add(qualCheckReq);
                qualCheckReq.setDescription(des);

                qualCheckReq.setStatus("Requested");
                qualCheckReq.setSender(ua);
                populateTechnicianRequest();
                JOptionPane.showMessageDialog(null, "Request send successfully");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select the request!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReqActionPerformed
        // TODO add your handling code here:
        ViewAllQualityCheckRequestsJPanel vaqualcheckreqJPanel = new ViewAllQualityCheckRequestsJPanel(container, ua, system);
        container.add("all quality check requests JPanel", vaqualcheckreqJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnViewReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnViewReq;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JTable tblNotifyQualityChecker;
    private javax.swing.JTextField txtProblemDesc;
    // End of variables declaration//GEN-END:variables
}
