/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommonLoginPage;

import Business.EcoSystem;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class CheckOutJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddToCartJPanel
     */
    private JPanel container;
    private UserAccount ua;
    private Organization org;
    private Order o;
    private EcoSystem system;
    Date nd = new Date();
    DateFormat oDateFormat = new SimpleDateFormat("MM-dd-yyyy");
    String szDate1 = oDateFormat.format(nd);
    Date newDate = addDays(nd, 30);
    String szDate = oDateFormat.format(newDate);

    public CheckOutJPanel(JPanel container, UserAccount ua, Organization org, Order o, EcoSystem system) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.org = org;
        this.o = o;
        this.system = system;
        populateOrder();
        btnBack.setEnabled(true);
        btnBack.setEnabled(false);
    }

    public void populateOrder() {
        DecimalFormat df = new DecimalFormat("#.00");
        DefaultTableModel dtm = (DefaultTableModel) tblAddedtoCart.getModel();
        dtm.setRowCount(0);

        for (OrderItem oi : o.getOrderItemList()) {
            Object row[] = new Object[4];
            row[0] = oi;
            row[1] = oi.getFood().getCode();
            row[2] = oi.getOrderItemQuantity();

            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomername1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAddedtoCart = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomername1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblCustomername1.setText("Checkout");
        add(lblCustomername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 240, 120, 40));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setText("Activity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 110, 40));

        tblAddedtoCart.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tblAddedtoCart.setForeground(new java.awt.Color(102, 0, 102));
        tblAddedtoCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Food", "Code", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAddedtoCart);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 690, 97));

        btnRequest.setBackground(new java.awt.Color(102, 102, 102));
        btnRequest.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnRequest.setText("Request");
        btnRequest.setMaximumSize(new java.awt.Dimension(200, 200));
        btnRequest.setMinimumSize(new java.awt.Dimension(200, 200));
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 170, 50));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, -1, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        btnBack.setEnabled(true);
        for (OrderItem oi : o.getOrderItemList()) {
            FoodRequest req = new FoodRequest();
            req.setFood(oi.getFood());
            req.setSender(ua);
            req.setStatus("Requested");
            req.setRequestQuantity(oi.getOrderItemQuantity());

            req.setDateOfPurchaseInString(szDate1);

            org.getWorkQueue().getWorkRequestList().add(req);
            ua.getWorkQueue().getWorkRequestList().add(req);
            system.getWorkQueue().getWorkRequestList().add(req);

        }
        JOptionPane.showMessageDialog(null, "Food Requested!");

        btnRequest.setEnabled(false);
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RequestForFoodJPanel bm = (RequestForFoodJPanel) component;
        bm.populateOrder();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    public static Date addDays(Date date, int days) {

        GregorianCalendar cal = new GregorianCalendar();
        cal.setTime(date);
        cal.add(Calendar.DATE, days);

        return cal.getTime();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JTable tblAddedtoCart;
    // End of variables declaration//GEN-END:variables
}
