/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommonLoginPage;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.QualityCheckRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class ViewAllQualityCheckRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CallTechnicianJPanel
     */
    private JPanel container;
    private UserAccount ua;
    private EcoSystem system;

    public ViewAllQualityCheckRequestsJPanel(JPanel container, UserAccount ua, EcoSystem system) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.system = system;
        populateRequestTable();
    }

    public void populateRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblQualityCheckRequests.getModel();
        dtm.setRowCount(0);

        for (WorkRequest work : system.getWorkQueue().getWorkRequestList()) {
            if (work instanceof QualityCheckRequest) {
                if (ua == work.getSender()) {
                    Object row[] = new Object[6];
                    row[0] = work.getFood().getName();
                    row[1] = work.getFood().getCode();
                    row[2] = work.getStatus();
                    row[3] = work.getReceiver();
                    row[4] = ((QualityCheckRequest) work).getServiceDateInString();

                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQualityCheckRequests = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblactivity1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblQualityCheckRequests.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblQualityCheckRequests.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tblQualityCheckRequests.setForeground(new java.awt.Color(102, 0, 102));
        tblQualityCheckRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Food", "Code", "Notify", "Quality Checker Name", "Date of assistance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblQualityCheckRequests);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 779, 173));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setText("Activity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 110, -1));

        lblactivity1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblactivity1.setText("All Quality Check Request");
        add(lblactivity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 290, 30));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, -1, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblactivity1;
    private javax.swing.JTable tblQualityCheckRequests;
    // End of variables declaration//GEN-END:variables
}
