/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodMinisterRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author
 */
public class FoodMinisterWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodMinisterWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;

    public FoodMinisterWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFoodRequests = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFoodRequests.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodRequests.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnFoodRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodRequests.setText("Food Requests from NGO");
        btnFoodRequests.setMaximumSize(new java.awt.Dimension(200, 200));
        btnFoodRequests.setMinimumSize(new java.awt.Dimension(200, 200));
        btnFoodRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodRequestsActionPerformed(evt);
            }
        });
        add(btnFoodRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 274, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFoodRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodRequestsActionPerformed
        // TODO add your handling code here:
        RequestsForFoodfromNGOJPanel rfjp = new RequestsForFoodfromNGOJPanel(userProcessContainer, business.getNetworkList(), business);
        userProcessContainer.add("request from NGO JPanel", rfjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnFoodRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoodRequests;
    // End of variables declaration//GEN-END:variables
}
