/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;

    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblNetwork.getModel();
        model.setRowCount(0);

        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = network.getName();
                row[1] = enterprise;
                row[2] = enterprise.getEnterpriseType().getValue();

                model.addRow(row);
            }
        }
    }

    private void populateComboBox() {
        networkCombo.removeAllItems();
        enterpriseCombo.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkCombo.addItem(network);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            enterpriseCombo.addItem(type);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetwork = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtEnterprise = new javax.swing.JTextField();
        btnCreateNetwork = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        enterpriseCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        networkCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNetwork.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        tblNetwork.setForeground(new java.awt.Color(102, 0, 102));
        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Network", "Enterprise Name", "Enterprise Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNetwork);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 640, 160));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel5.setText("Enterprise Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 130, -1));

        txtEnterprise.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterpriseActionPerformed(evt);
            }
        });
        txtEnterprise.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnterpriseKeyPressed(evt);
            }
        });
        add(txtEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 244, 28));

        btnCreateNetwork.setBackground(new java.awt.Color(102, 102, 102));
        btnCreateNetwork.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnCreateNetwork.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNetwork.setText("Add Enterprise");
        btnCreateNetwork.setMaximumSize(new java.awt.Dimension(200, 200));
        btnCreateNetwork.setMinimumSize(new java.awt.Dimension(200, 200));
        btnCreateNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNetworkActionPerformed(evt);
            }
        });
        add(btnCreateNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 610, 250, 50));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setText("Activity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 110, -1));

        lblCustomername1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblCustomername1.setText("Enterprise");
        add(lblCustomername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 170, 130, -1));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 620, -1, 39));

        enterpriseCombo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        enterpriseCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 244, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel7.setText("Enterprise Type :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 130, -1));

        networkCombo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        networkCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboActionPerformed(evt);
            }
        });
        add(networkCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 244, 29));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel8.setText("Network :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNetworkActionPerformed
        // TODO add your handling code here:
        if (!txtEnterprise.getText().equals("")) {
            Network network = (Network) networkCombo.getSelectedItem();
            Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseCombo.getSelectedItem();

            if (network == null || type == null) {
                JOptionPane.showMessageDialog(null, "Please select the input");
                return;
            }

            String name = txtEnterprise.getText();

            Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);

            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please enter name", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnCreateNetworkActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel swjp = (SystemAdminWorkAreaJPanel) component;
        swjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEnterpriseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnterpriseKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
            txtEnterprise.setEditable(false);
            txtEnterprise.setBackground(Color.red);
        } else {
            txtEnterprise.setEditable(true);
            txtEnterprise.setBackground(Color.WHITE);
        }

    }//GEN-LAST:event_txtEnterpriseKeyPressed

    private void networkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkComboActionPerformed

    private void txtEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNetwork;
    private javax.swing.JComboBox enterpriseCombo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JComboBox networkCombo;
    private javax.swing.JTable tblNetwork;
    private javax.swing.JTextField txtEnterprise;
    // End of variables declaration//GEN-END:variables
}
