/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.EcoSystem;
import Business.Food.Food;
import Business.Food.Food.FoodType;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class AddNewfoodJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewfoodJPanel
     */
    private JPanel container;
    private EcoSystem business;
    private UserAccount ua;
    private Supplier s;
    private Food food;

    public AddNewfoodJPanel(JPanel container, UserAccount ua, Supplier s, EcoSystem business) {
        initComponents();
        this.container = container;
        this.business = business;
        this.ua = ua;
        this.s = s;
        populateFoodType();
        populateSupplierTable();
    }

    public void populateFoodType() {
        jcbFoodType.removeAllItems();;
        for (FoodType type : Food.FoodType.values()) {
            jcbFoodType.addItem(type);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        txtFoodName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcbFoodType = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAddFood = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierFoodDetails = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnDeleteFood = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setText("Activity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 120, -1));

        lblCustomername1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblCustomername1.setForeground(new java.awt.Color(51, 51, 51));
        lblCustomername1.setText("Add New Food");
        add(lblCustomername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 180, -1));

        txtFoodName.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtFoodName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoodNameActionPerformed(evt);
            }
        });
        txtFoodName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFoodNameKeyPressed(evt);
            }
        });
        add(txtFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 285, 27));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel9.setText("Food Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 100, -1));

        jcbFoodType.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jcbFoodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jcbFoodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 178, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel11.setText("Food Type");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 90, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel12.setText("Quantity");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 90, -1));

        txtQuantity.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
        });
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 285, 27));

        btnAddFood.setBackground(new java.awt.Color(102, 102, 102));
        btnAddFood.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnAddFood.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFood.setText("Add Food");
        btnAddFood.setMaximumSize(new java.awt.Dimension(200, 200));
        btnAddFood.setMinimumSize(new java.awt.Dimension(200, 200));
        btnAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodActionPerformed(evt);
            }
        });
        add(btnAddFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 170, 40));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, -1, 39));

        tblSupplierFoodDetails.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        tblSupplierFoodDetails.setForeground(new java.awt.Color(102, 0, 102));
        tblSupplierFoodDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Food", "Code", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSupplierFoodDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 641, 142));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel14.setText("Food Catalog");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 130, -1));

        btnDeleteFood.setBackground(new java.awt.Color(102, 102, 102));
        btnDeleteFood.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnDeleteFood.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFood.setText("Delete Food");
        btnDeleteFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFoodActionPerformed(evt);
            }
        });
        add(btnDeleteFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodNameActionPerformed

    private void txtFoodNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodNameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
            txtFoodName.setEditable(false);
            txtFoodName.setBackground(Color.red);
        } else {
            txtFoodName.setEditable(true);
            txtFoodName.setBackground(Color.WHITE);
        }

    }//GEN-LAST:event_txtFoodNameKeyPressed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        // TODO add your handling code here:

        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == evt.VK_BACK_SPACE)) {
            txtQuantity.setEditable(true);
            txtQuantity.setBackground(Color.white);
        } else {
            txtQuantity.setEditable(false);
            txtQuantity.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtQuantityKeyPressed

    public void populateSupplierTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblSupplierFoodDetails.getModel();
        dtm.setRowCount(0);
        for (Food m : s.getFoodList().getFoodCatalog()) {
            Object row[] = new Object[4];
            row[0] = m;
            row[1] = m.getCode();
            row[2] = m.getQuantity();

            dtm.addRow(row);
        }
    }
    private void btnAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodActionPerformed

        String foodName = txtFoodName.getText();
        String xz = txtQuantity.getText();
        try {
            if ((foodName.equals("")) || (xz.equals(""))) {
                throw new IllegalArgumentException();
            }
            try {
                int qty = Integer.parseInt(txtQuantity.getText());

                Food.FoodType type = (Food.FoodType) jcbFoodType.getSelectedItem();

                int temp = 0;

                if (type == null) {
                    JOptionPane.showMessageDialog(null, "Please select a Food type");
                    return;
                }

                for (Food m : s.getFoodList().getFoodCatalog()) {
                    if (foodName.equals(m.getName())) {
                        temp = 1;
                        m.setQuantity(m.getQuantity() + qty);
                    }
                }
                if (temp == 0) {
                    Food m = s.getFoodList().addFood();
                    m.setName(foodName);
                    m.setQuantity(qty);

                    m.setType(type.getValue());
                    Date today = new Date();
                    DateFormat oDateFormat = new SimpleDateFormat("MM-dd-yyyy");
                    String todayDate = oDateFormat.format(today);
                    m.setDateOfEntry(today);
                    m.setDateOfEntryInString(todayDate);
                }
                populateSupplierTable();
                txtFoodName.setText("");

                txtQuantity.setText("");

            } catch (NumberFormatException n) {

            }
        } catch (IllegalArgumentException I) {
            JOptionPane.showMessageDialog(null, "Please input value");
        }
    }//GEN-LAST:event_btnAddFoodActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFoodActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSupplierFoodDetails.getSelectedRow();
        food = (Food) tblSupplierFoodDetails.getValueAt(selectedRow, 0);
        System.out.println(selectedRow);
        if (selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete this food?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {

                s.getFoodList().removeFood(food);
                populateSupplierTable();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnDeleteFoodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFood;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteFood;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbFoodType;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JTable tblSupplierFoodDetails;
    private javax.swing.JTextField txtFoodName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
