/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount ua;
    private EcoSystem system;
    private SupplierOrganization org;
    private Supplier s;

    public SupplierWorkAreaJPanel(JPanel userProcessContainer, UserAccount ua, Organization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.system = system;
        System.out.println(this.system);
        this.org = (SupplierOrganization) organization;
        lblSupplierName.setText(ua.getEmployee().getName());

        for (Supplier supplier : this.system.getSupplierCatalog().getSupplierList()) {
            if (this.ua.getEmployee().getName().equalsIgnoreCase(supplier.getSupplierName())) {
                this.s = supplier;
                System.out.println(s);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomername1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnFoodRequest = new javax.swing.JButton();
        lblSupplierName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAddFood = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        lblCustomername1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblCustomername1.setText("Supplier Work Area");
        add(lblCustomername1);
        lblCustomername1.setBounds(840, 120, 240, 33);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setText("Activity:");
        add(jLabel6);
        jLabel6.setBounds(720, 120, 110, 33);

        btnFoodRequest.setBackground(new java.awt.Color(102, 102, 102));
        btnFoodRequest.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnFoodRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodRequest.setText("View Food Request");
        btnFoodRequest.setMaximumSize(new java.awt.Dimension(200, 200));
        btnFoodRequest.setMinimumSize(new java.awt.Dimension(200, 200));
        btnFoodRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodRequestActionPerformed(evt);
            }
        });
        add(btnFoodRequest);
        btnFoodRequest.setBounds(800, 430, 213, 60);

        lblSupplierName.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblSupplierName.setText("*Supplier name");
        add(lblSupplierName);
        lblSupplierName.setBounds(840, 190, 200, 33);

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel7.setText("Name:");
        add(jLabel7);
        jLabel7.setBounds(720, 180, 80, 40);

        btnAddFood.setBackground(new java.awt.Color(102, 102, 102));
        btnAddFood.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnAddFood.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFood.setText("Add Food");
        btnAddFood.setMaximumSize(new java.awt.Dimension(200, 200));
        btnAddFood.setMinimumSize(new java.awt.Dimension(200, 200));
        btnAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodActionPerformed(evt);
            }
        });
        add(btnAddFood);
        btnAddFood.setBounds(800, 330, 213, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFoodRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodRequestActionPerformed
        // TODO add your handling code here:
        ViewFoodRequestJPanel viewFoodReqJp = new ViewFoodRequestJPanel(userProcessContainer, ua, s, system);
        userProcessContainer.add("view food JPanel", viewFoodReqJp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_btnFoodRequestActionPerformed

    private void btnAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodActionPerformed
        // TODO add your handling code here:
        AddNewfoodJPanel addFoodJp = new AddNewfoodJPanel(userProcessContainer, ua, s, system);
        userProcessContainer.add("add new Food JPanel", addFoodJp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_btnAddFoodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFood;
    private javax.swing.JButton btnFoodRequest;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel lblSupplierName;
    // End of variables declaration//GEN-END:variables
}
