/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.EcoSystem;
import Business.Food.Food;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class ViewFoodRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFoodRequestJPanel
     */
    private JPanel container;
    private EcoSystem system;
    private UserAccount ua;
    private Supplier s;

    public ViewFoodRequestJPanel(JPanel container, UserAccount ua, Supplier s, EcoSystem system) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.system = system;
        this.s = s;
        populateTable();
        estimatedDate.setDate(new Date());

    }

    public void populateTable() {

        boolean flag;

        DefaultTableModel model = (DefaultTableModel) tblFoodRequests.getModel();

        model.setRowCount(0);
        flag = false;
        for (WorkRequest work : system.getWorkQueue().getWorkRequestList()) {
            if (work instanceof FoodRequest) {
                if (work.getStatus().equals("Pending") || work.getStatus().equals("Completed")) {
                    Object[] row = new Object[8];
                    row[0] = work;
                    row[1] = work.getFood();
                    row[2] = work.getFood().getCode();
                    row[3] = ((FoodRequest) work).getRequestQuantity();
                    row[4] = work.getSender();
                    row[5] = work.getReceiver();
                    row[6] = work.getStatus();
                    row[7] = work.getDayOfDelivery();
                    model.addRow(row);
                    flag = true;
                }
            }
            if (flag == false) {
                JOptionPane.showMessageDialog(null, "Please Add Foods");

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblCustomername1 = new javax.swing.JLabel();
        lblCustomername3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFoodRequests = new javax.swing.JTable();
        btnAssigntoMe = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        estimatedDate = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setText("Activity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 110, -1));

        lblCustomername1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        lblCustomername1.setText("Requests for Food");
        add(lblCustomername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 230, -1));

        lblCustomername3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        lblCustomername3.setText("Estimated Date of Delivery");
        add(lblCustomername3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 190, -1));

        tblFoodRequests.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        tblFoodRequests.setForeground(new java.awt.Color(102, 0, 102));
        tblFoodRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Food", "Code", "Quantity", "Sender", "Receiver", "Status", "Date Of Delivery"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFoodRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 900, 230));

        btnAssigntoMe.setBackground(new java.awt.Color(102, 102, 102));
        btnAssigntoMe.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnAssigntoMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssigntoMe.setText("Assign to Me");
        btnAssigntoMe.setMaximumSize(new java.awt.Dimension(200, 200));
        btnAssigntoMe.setMinimumSize(new java.awt.Dimension(200, 200));
        btnAssigntoMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssigntoMeActionPerformed(evt);
            }
        });
        add(btnAssigntoMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, 170, 50));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 60, 39));

        estimatedDate.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        estimatedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimatedDateActionPerformed(evt);
            }
        });
        add(estimatedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssigntoMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssigntoMeActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        int selectedRow = tblFoodRequests.getSelectedRow();

        if (selectedRow >= 0) {
            FoodRequest req = (FoodRequest) tblFoodRequests.getValueAt(selectedRow, 0);

            if (req.getStatus().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed");
                return;
            }
            for (Food m : s.getFoodList().getFoodCatalog()) {
                if (req.getFood().equals(m)) {
                    flag = true;
                    Date oDate = estimatedDate.getDate();
                    Date now = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
                    if ((sdf.format(oDate).equals(sdf.format(now))) || (sdf.format(oDate).compareTo(sdf.format(now))) > 0) {
                        DateFormat oDateFormat = new SimpleDateFormat("MM-dd-yyyy");
                        String szDate = oDateFormat.format(oDate);
                        req.setReceiver(this.ua);
                        req.setStatus("Completed");

                        req.setDayOfDelivery(szDate);

                        estimatedDate.setDate(oDate);
                        populateTable();
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Date of Delivery");
                        return;
                    }
                }
            }
            if (flag == false) {
                JOptionPane.showMessageDialog(null, "You cannot request as you dont have the food!!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Request to process");
            return;
        }

    }//GEN-LAST:event_btnAssigntoMeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void estimatedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimatedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimatedDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigntoMe;
    private javax.swing.JButton btnBack;
    private org.jdesktop.swingx.JXDatePicker estimatedDate;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomername1;
    private javax.swing.JLabel lblCustomername3;
    private javax.swing.JTable tblFoodRequests;
    // End of variables declaration//GEN-END:variables
}
